### ISSUE TITLE
What exactly does ignoreType do?

### ISSUE THREAD

**Issue by mrubin** [marmelroy/PhoneNumberKit#129]
I read #92 and I skimmed the code, but I don't follow what exactly "hard type validation" is. Could you please explain? What validation would I be giving up if I used `ignoreType: true`?

Thank you!

**Comment by marmelroy** [comment]
The basic validation checks if a phone number conforms to a country's regex.

The type validation checks every single regexp within the country in order to be able to tell you the phone number's type (i.e. fixed line / mobile / premium rate etc). The type is captured in the PhoneNumber object. 

This is quite an expensive operation and can slow parsing down significantly so using 'ignoreType' will speed things up for you if you are parsing a lot of numbers. Also, if the 'type' returns 'unknown', that's considered an error.
