### ISSUE TITLE
slow init for PhoneNumberTextField

### ISSUE THREAD

**Issue by jpstern** [marmelroy/PhoneNumberKit#196]
Specifically on older devices, initializing a PhoneNumberTextField instance results in a pretty significant lag (~280ms).  Very noticeable when trying to perform view controller transitions.  I believe this is because it is reinitializing the PhoneNumberKit instance each time.  

Is it possible to pre-load the PhoneNumberKit instance to speed this up?  

A potentially solution could be to change the phoneNumberKit instance to be a static or shared instance, so at least it would only be slow for the first load.

**Comment by Intuiso** [comment]
Even though I really like the PhoneNumberKit, the behavior described by @jpstern is really making PhoneNumberTextFields almost unusable. A static sharedInstance might really  resolve the issue.

**Comment by mikengyn** [comment]
> Even though I really like the PhoneNumberKit, the behavior described by @jpstern is really making PhoneNumberTextFields almost unusable. A static sharedInstance might really resolve the issue. (Or does anything speak against that?)
> 
> I tried it by adding
> ` public static let sharedInstance: PhoneNumberKit = PhoneNumberKit.init()`
> to the PhoneNumberKit class.
> 
> Then, I changed PhoneNumberTextField to use the sharedInstance:
> `open class PhoneNumberTextField: UITextField, UITextFieldDelegate {`
> ` let phoneNumberKit = PhoneNumberKit.sharedInstance`
> 
> Moreover, I am using the PartialFormatter convenience init a few times. So, I set the convenience init to also use the sharedInstance:
> `public convenience init(phoneNumberKit: PhoneNumberKit = PhoneNumberKit.sharedInstance,`
> ` defaultRegion: String = PhoneNumberKit.defaultRegionCode(),`
> ` withPrefix: Bool = true) {`
> `...`
> `}`
> 
> Really helps a lot in terms of performance. However, I still did not like the first initialization when the sharedInstance was called the first time. So, I call it directly in the AppDelegate in the asynchronous queue. Even though not being a really nice solution, it again helps the performance on old devices.
> 
> `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {`
> ` DispatchQueue.main.async {`
> ` // Initialization is very slow. So perform it once on startup`
> ` let _ = PhoneNumberKit.sharedInstance`
> ` }`
> ` return true`
> ` }`

This works great, thanks for sharing.

**Comment by traviskaufman** [comment]
FWIW I was able to trace this down to what I *believe* is the culprit: 

![image](https://user-images.githubusercontent.com/1185269/66243229-d0f85600-e6d1-11e9-8a52-188659381950.png)

Looks like phone number kit [parses metadata JSON](https://github.com/marmelroy/PhoneNumberKit/blob/master/PhoneNumberKit/PhoneNumberKit.swift#L24) on initialization, which by default [reads from a file](https://github.com/marmelroy/PhoneNumberKit/blob/master/PhoneNumberKit/PhoneNumberKit.swift#L178-L185). 

I think the right solution here for `PhoneNumberTextField` would be to modify the constructor to accept a `PhoneNumberKit` instance, e.g. 

```swift
init(withPhoneNumberKit phoneNumberKit: PhoneNumberKit? = nil)
```

Happy to contribute if you're currently maintaining / accepting contributions @marmelroy ! Otherwise, going with @Intuiso 's fantastic solution :)
