### ISSUE TITLE
Breaks QuickType entry of phone numbers

### ISSUE THREAD

**Issue by RobinDaugherty** [marmelroy/PhoneNumberKit#221]
When a user chooses one of their phone numbers using QuickType (autocomplete), the entire string is filtered and does not appear in the field.

**Comment by bwhtmn** [comment]
I was able to work around this issue by adding a UITextFieldDelegate to my PhoneNumberTextField with the following code:

```
    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        phoneNumberTextField.isPartialFormatterEnabled = !(range.location == 0 && range.length == 0 && string == " ")
        return true
    }
```

It's a hack, but it works. Would be better if this was fixed in PhoneNumberKit itself.

**Comment by RobinDaugherty** [comment]
Thanks @bwhtmn can you explain what this does? I saw this change in your fork, but without a comment or explanation it's hard to know what this might break. It looks like it disables the formatter completely, which is probably not what I want to do.

**Comment by bwhtmn** [comment]
@RobinDaugherty The change in my comment above (not a fork, I think?) does turn off the partial formatter temporarily, but only in one situation. I found that QuickType always begins by inserting a blank space at the start of the text field, so I detect this situation and temporarily disable the partial formatter. Any other text typed will result in the partial formatter being enabled. Since the delegate is evaluated before the isPartialFormatterEnabled property, this should be fine. See lines 210-215 in TextField.swift
