### ISSUE TITLE
Validation issue for Vietnamese number (e.g. +84385735521)

### ISSUE THREAD

**Issue by IgorKovr** [marmelroy/PhoneNumberKit#242]
A real Vietnamese number is not validated
+84385735521

**Comment by joshuakcockrell** [comment]
@IgorKovr @abdultcb libphonenumber updated Vietnam metadata in release 8.10.1 in November 2018. Does this phone number format correctly in the current libphonenumber javascript demo? https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

If it formats correctly in that page I linked to, then we probably just need to update the PhoneNumberKit metadata since it hasn't been updated since Sept 2018.

**Comment by kuyazee** [comment]
Will be fixed with PR #281
