### ISSUE TITLE
Ignore phone number validation

### ISSUE THREAD

**Issue by WingYn** [marmelroy/PhoneNumberKit#257]
It isn't possible to get the formatting of a phone number if the phone number is invalid?

I am using test phone numbers when developing so I would like to be able to pass in phone numbers like +11234567890. But this doesn't work.

So is there any way to disable phone number validation?

**Comment by joshuakcockrell** [comment]
@WingYn I'm not sure what country/region you are trying this from, but the problem with the number +11234567890 isn't validation, it's that the area code is 123, but area codes start in the 200's in the US. See this link for a complete list of US area codes: https://www.areacodelocations.info/areacodelist.html

There is no known format to use to display the number you gave and since the E164 format is invalid, and the international format is invalid, the correct format is simply "+11234567890"

I would suggest you use a test number like +12004567890, or anything where the area code is 200 or above. +15555555555 is a pretty standard test number.

This is all assuming a US region code. I'm sure you could find good test numbers to use for whatever region you're developing for.

You can use this tool made by Google to see how different numbers will be formatted.
https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
