### ISSUE TITLE
v2.6.0 works incorrectly in production

### ISSUE THREAD

**Issue by qgliu** [marmelroy/PhoneNumberKit#259]
Everything is flawless in development mode. Once we upload it to Apple, the test flight version doesn't work anymore. It doesn't format nor validates correctly.

After downgrading to 2.5.1, it works fine.

**Comment by marmelroy** [comment]
hi @qgliu (and @mime29) can you share more details about the set up and ways to reproduce? 

what exactly are you experiencing when you say it "doesn't format nor validates correctly."?

Thanks,
Roy

**Comment by mime29** [comment]
I get (if I may) "crazy" logs here and parsing doesn't work on 2.6.0


```
Remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
[NetworkInfo] Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
 [Client] Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
PhoneNumberKit.PhoneNumberError.notANumber
```

**Comment by marmelroy** [comment]
interesting, that seems to be core telephony related (which we use to know the user's current phone language). 

What simulator and which version of Xcode? Can you confirm that you're not getting the same log with 2.5.1?

**Comment by qgliu** [comment]
In development I use either iPad Air 2 simulator or real iPads, they work fine. I don't see an error in the log. I use Xcode version 10.1.

Once uploaded for TestFlight, I use an iPad with the same model as for development.

In development, a 10-digit US number would be formatted as (505) 555 5555, but the version in TestFlight would be 5055555555. When you enter a valid phone number to PhoneNumberTextField and the call to `isValidNumber` would return false. It returns true in development mode.

Since this only happens in the version submitted to Apple, I can't provide a log.

> interesting, that seems to be core telephony related (which we use to know the user's current phone language).
> 
> What simulator and which version of Xcode? Can you confirm that you're not getting the same log with 2.5.1?

**Comment by mime29** [comment]
After further testing, on simulator it's working fine as well but the error logs are there.
`The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.`

**Comment by klemenzagar91** [comment]
I have exactly the same problem. I run it on the simulator and if I try to parse phone number 031 774 305 i got back the result that phone number is not valid.

**Comment by joshuakcockrell** [comment]
@mime29 @qgliu @marmelroy  I cannot reproduce this in production. I have updated my app to 2.6 and it's correctly validating and formatting numbers in production.

**Comment by joshuakcockrell** [comment]
@klemenzagar91 What country code are you using to validate 031774305? US area codes start at 200 so the area code 031 is not a valid US area code. Can you get this number to format or validate correctly using Google's javascript demo? https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

**Comment by mime29** [comment]
@joshuakcockrell as i wrote a bit before, it's actually working fine. "fine" because the lib generates (maybe through iOS SDK, I don't know) lots of error logs. It's not really nice to have a library generating error logs when you try to keep your console log clean. Also it's counter intuitive. Either it works and it should log nothing either it doesn't and shows the error.

**Comment by klemenzagar91** [comment]
The country of the phone number that I provide is Slovenia. But this number is fetched from the user's address book, so I cannot know for sure that it should be parsed with setting for Slovenia.

So if I use your library for parsing and not select any specific country, it doesn't parse the phone number.

**Comment by joshuakcockrell** [comment]
@klemenzagar91 So you are trying to format a local number from Slovenia, but you don't want to tell PhoneNumberKit that it's a Slovenian number. No wonder it's not formatting correctly!

First off, you should know this isn't just a PhoneNumberKit problem. Just try to type that number into your iPhone (assuming you have an iPhone because this is a Swift library). Chances are unless your phone is set to Slovenia it's not going to format correctly because it doesn't know the region code. Don't expect ANY phone formatting library you use to know how to correctly parse a number like this without giving it a region code.

If you don't want to provide a region code, PhoneNumberKit is still smart enough to infer the region code from the 386 Slovenian country code. You have to add a + sign to the front to specify an international dialing prefix, and you have to add the 386 country code. Try typing the number +38631774305 into your iPhone and you will see it knows how to format that correctly even if you aren't on Slovenian settings. PhoneNumberKit will do the same.

If this number is being provided by your users and you don't have control of adding a +386 to the front of the number for some reason, then honestly too bad. They don't want to tell you it's a SI region code, AND they don't want to tell you that it's a +386 country code, then they can't expect that you are going to know how to format this number correctly for them.

In any case, this definitely has nothing to do with the **v2.6.0 works incorrectly in production** issue, so you should open a new issue if you want to discuss further.
