### ISSUE TITLE
Number cannot be parsed with unknown region. Region should be optional.

### ISSUE THREAD

**Issue by janmarek** [marmelroy/PhoneNumberKit#265]
```
public func parse(_ numberString: String, withRegion region: String = PhoneNumberKit.defaultRegionCode(), ignoreType: Bool = false) throws -> PhoneNumber
```

Parse function uses defaultRegion so you can only parse numbers from your region.

**Comment by joshuakcockrell** [comment]
[libphonenumber uses "ZZ" as the official code for the unknown region.](https://github.com/googlei18n/libphonenumber/blob/8ce872181bda65b1503c754c5d0ea5aab4f070e5/java/libphonenumber/test/com/google/i18n/phonenumbers/RegionCode.java#L62) But after some simple searches through the PhoneNumberKit metadata &
 code I don't see any references to "ZZ" What happens when you try to pass in ZZ as the string here?

**Comment by basememara** [comment]
I was just looking at this today. Instead of trying to derive the country code from the device, the code for `PhoneNumberKit.defaultRegionCode()` is dynamic and looks pretty good: https://github.com/marmelroy/PhoneNumberKit/blob/8c3efc6f6169f805266f3db15c61e85697cdd576/PhoneNumberKit/PhoneNumberKit.swift#L156

If it isn't enough for you, why don't you pass in your own country code?

**Comment by janmarek** [comment]
@basememara I just want to validate if given phone number is valid. No assumptions about country.

**Comment by kuyazee** [comment]
Is this still an issue @janmarek? I do believe that for this library to know if a number is valid or not a country needs to be assumed and It can detect the phone number's country automatically for you, and as @basememara said

> the code for PhoneNumberKit.defaultRegionCode() is dynamic

Just reopen this ticket if it's still an issue
