### ISSUE TITLE
Unit Tests Fail

### ISSUE THREAD

**Issue by romayev** [marmelroy/PhoneNumberKit#310]
I opened the project with Xcode Version 11.1 (11A1027) on macOS Mojave 10.14.6. I tried running the unit tests and most of them are failing. Specifically, testUSMetadata fails on line 37 with:

Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

It appears that the territories array is empty.

<img width="268" alt="image" src="https://user-images.githubusercontent.com/11178980/67952033-0144ee80-fbc3-11e9-8760-ecda2bf93c29.png">

**Comment by dmcgloin** [comment]
Seeing this too in Xcode 11.2. Currently trying to understand why `territories` array is empty

**Comment by kuyazee** [comment]
I just ran the same test using Xcode 11.0 on the latest branch and it only failed for me because US's metadata has updated `testUSMetadata() line:49`, but besides that I'm not seeing this issue.

I'll update my Xcode tonight and will also investigate why this is happening, if you have any ideas please tell me, as for a fix maybe what we could do is change the `territories` key to have a custom init with a default empty array value.

**Comment by marmelroy** [comment]
This is now fixed. Closing
