### ISSUE TITLE
App store rejection

### ISSUE THREAD

**Issue by sethsamuel** [marmelroy/PhoneNumberKit#386]
We're having a recurring problem where somehow the App Store reviewer is entering text into the field that isn't being formatted and is somehow malformed when `.text` is called. They refuse to give us any information about how they're achieving this, but was hoping someone else had encountered and had a workaround that could be mainlined into the this otherwise great library.
![attachment Screenshot-0714-085925](https://user-images.githubusercontent.com/9062418/87431054-124c5900-c5b4-11ea-962d-f319295f6316.png)

**Comment by rromanchuk** [comment]
@sethsamuel  it was a while ago but i'm almost positive this happened to me as well, and it was a head scratcher. Was this their attached screenshot? I have multiple hacks in place just for their weird ipad emulator, that is somehow injecting state that can't normally happen. 

I'm just looking at my code to figure out what i did. It looks like i take `text!`, and assume it's malformed because apple is most likely doing something that doesn't allow formatting to run. I then programmatically run it through format to sanitize as it should have been. If it doesn't validate client side i still submit to backend so at least i have a chance to deal with it, and use http response for the actually validation error. Previously client side was handling the validation, which was basically swallowing a weird edge, and much harder to debug. 

Also had to put in the most hideous hack/quickfix just to handle an obstructed view when they tested with ipad. They lovveeeee testing iphone apps on the ipad.

```swift
@IBAction func sendSMS(_: AnyObject) {
  formattedPhoneNumber = phoneTextField.text!

  do {
      let parsedPhoneNumber = try phoneNumberKit.parse(formattedPhoneNumber)
      formattedPhoneNumber = phoneNumberKit.format(parsedPhoneNumber, toType: .e164)
  } catch {
      Crashlytics.crashlytics().record(error: error)
      // DONT BLOCK next step, just let backend try to deal with this number
  }
}

@objc func keyboardWillShow(_ notification: Notification) {
    if let info = (notification as NSNotification).userInfo {
        if let animationDuration = info[UIResponder.keyboardAnimationDurationUserInfoKey] as? Double, let keyboardSize = (info[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue)?.cgRectValue {
            buttonsMarginBottom.constant = keyboardSize.height + 29
            // check if running on iPad emulator and adjust top margin to allow everything to fit
            if UIScreen.main.bounds.height < 550 { marginTop.constant = 30 }
            UIView.animate(withDuration: animationDuration, animations: {
                self.view.layoutIfNeeded()
            })
        }
    }
}

@objc func keyboardWillHide(_ notification: Notification) {
    if let info = (notification as NSNotification).userInfo {
        if let animationDuration = info[UIResponder.keyboardAnimationDurationUserInfoKey] as? Double {
            buttonsMarginBottom.constant = 29
            // check if running on iPad emulator and adjust top margin to allow everything to fit
            if UIScreen.main.bounds.height < 550 { marginTop.constant = 82 }
            UIView.animate(withDuration: animationDuration, animations: {
                self.view.layoutIfNeeded()
            })
        }
    }
}

```

**Comment by sethsamuel** [comment]
Finally found the underlying cause here. If you don't explicitly set a default country, PhoneNumberKit does its best to detect the phone's region. We provide a US 800 number tied to a test account for Apple, but when we were pulling a Chinese based tester from their pool, PNK would attach a Chinese country code, thus creating an invalid phone number.
