### ISSUE TITLE
Maximum Characters for PhoneNumberTextField

### ISSUE THREAD

**Issue by LeakedDave** [marmelroy/PhoneNumberKit#58]
Any chance you could add a check for the maximum number of characters in PhoneNumberTextField? The input shouldn't allow more than the international format number should be, right?

Really appreciate this plugin btw :)

**Comment by marmelroy** [comment]
Hi @LeakedDave, thanks for the idea! 

The issue here is that there isn't really a maximum character count we can safely use. Not only do phone number lengths differ by country but they can differ in unpredictable ways (think extensions). Adding a hard limit in the framework level can cause a lot of damage to specific use cases...
