### ISSUE TITLE
Instance is relatively expensive to allocate - Performance

### ISSUE THREAD

**Issue by fstigre** [marmelroy/PhoneNumberKit#633]
Hi, I apologize for posting this as an issue but I have no other way to ask. I'm about to start using this library but I noticed some advice from the developer that I'm concerned with. It says that the instance is relatively expensive to allocate and that you need to make sure to deallocate it when no longer needed. It also mentions that the validation could be quite costly performance-wise.

Can someone please elaborate a little more on the following two statements? Is there anything special that needs to be done, how would you deallocate the instance? I looked at the sample project and I couldn't see how this was done.  I thought the compiler takes care of this in Swift (ARC).

As far as performance, what would be the best way to validate a number? And how bad would the performance be?

 >> A PhoneNumberKit `instance is relatively expensive to allocate` (it parses the metadata and keeps it in memory for the object's lifecycle), you should try and make sure PhoneNumberKit is allocated once and deallocated when no longer needed.

>> To parse a string, use the parse function. The region code is automatically computed but can be overridden if needed. PhoneNumberKit automatically does a hard type validation to ensure that the object created is valid, `this can be quite costly performance-wise` and can be turned off if needed.

### EDIT: I tried parsing as the user types and it seems very responsive, but I try to only parse after the 6 character to minimize the number of parses.  I'm using it in `SwiftUI`, inside the `onChange` modifier.

Thanks a lot!

**Comment by bguidolim** [comment]
Hey @fstigre 

The first sentence is correct, the metadata is quite expensive because it has all the rules and regex for all existing regions worldwide. The instance will be deallocated via ARC, or you can force it, making a property optional and setting it to `nil` when you believe you don't need it anymore.

The parsing is fast, I would say, if you simply use a string without specifying a region, it can take some milliseconds more to parse it correctly, if you specify the region, it can be faster.
When parsing, you can also ask the library to ignore the type (mobile, landline, etc.), making it faster too.

I don't think you need to create any rule to start the parsing after 6 characters, you will be OK with the default implementation.
