### ISSUE TITLE
Argentina mask doesn't match the actual number

### ISSUE THREAD

**Issue by EmmaVvv** [marmelroy/PhoneNumberKit#655]
We've noticed that Argentina phone number formatting is broken when user follows the mask, but it works without 9 at the beginning, so that can be a misleading behavior for users. 
Let me attach screenshots 

Below is the mask from framework (9 11 2345-6789):

![243714979-ec44aee5-d3fd-469a-9004-6c87b49d54cd](https://github.com/marmelroy/PhoneNumberKit/assets/53192422/571b5f9b-ef73-446e-9b21-e8296dae77da)

Here is how phone number formatting looks based on that mask:

![243715386-f6cb8779-158e-40d1-951e-38e5eaef4a9b](https://github.com/marmelroy/PhoneNumberKit/assets/53192422/0375acfc-17e1-4d54-a7a2-a2d04decf493)

And here is how formatting works (properly) without 9 in the beginning:

![243716640-e3f28bde-13df-4d86-bd5a-61a8b18370c7](https://github.com/marmelroy/PhoneNumberKit/assets/53192422/599d587d-68d9-4bb4-bdfd-7bddd523ae2f)

We're using latest 3.6.0 version via Cocoapods

**Comment by bguidolim** [comment]
Hey @EmmaVvv 

I see the issue and can confirm it's an issue with the `PartialFormatter`. However, it's not an issue with `PhoneNumberKit` itself but with the metadata provided by [libPhoneNumber](https://github.com/google/libphonenumber).

That's why I kindly ask people to check the [JS implementation](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html) before opening an issue here.

As you can see in the screenshot below, it's a common issue with the original library. I suggest you reach the discussing group of libPhoneNumber or report the issue there.

<img width="700" alt="Screenshot 2023-06-12 at 15 14 20" src="https://github.com/marmelroy/PhoneNumberKit/assets/987360/95df55d2-ac00-4dc3-aad3-432311d1d300">
