### ISSUE TITLE
PhoneNumberKit.defaultRegionCode() wrongly returns country code based on language on macOS

### ISSUE THREAD

**Issue by xhruso00** [marmelroy/PhoneNumberKit#694]
Current PhoneNumberKit.defaultRegionCode implementation calls `"CNContactsUserDefaults.shared().countryCode.uppercased()".`

This resolves as a call to `-[CNFoundationUserDefaults countryCode]` from private framework "ContactsFoundation.framework" which is implemented as `[userDefaults objectForKey:@"ABDefaultAddressCountryCode"];`

The userdefaults are pulled from file LocalizedDefaults.plist within Resources folder. Each language has it's own plist. 

Haven't tested this on iOS.

Expected result:
Region set to Slovakia will return "SK"

Current result:
Returns "GB" because my language is set to English(UK). 

Environment:
macOS 13.5.1

```
Example of en_GB.lproj->LocalizedDefaults.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ABDefaultAddressCountryCode</key>
	<string>gb</string>
	<key>ABNameSortingFormat</key>
	<string>sortingLastName sortingFirstName</string>
	<key>ABNewContactNameDisplay</key>
	<integer>0</integer>
</dict>
</plist>
```

**Comment by xhruso00** [comment]
Private framework "ContactsFoundation.framework" contains `[CNPhoneNumberHelper defaultCountryCode]` which resolves into `[[NSLocale currentLocale] objectForKey:@"NSLocaleCountryCode"]`. These calls are private methods but they indicate that this library current implementation is incorrect.

**Comment by bguidolim** [comment]
PNK doesn't use any private framework and you can check it's available for macOS: https://developer.apple.com/documentation/contacts/cncontactsuserdefaults/1403200-countrycode

The issue you're facing is probably because of permissions. For macOS, the app must have access to Contacts (System Preferences > Privacy & Security > Contacts).

For the first time, the system will ask for permission, but if you don't allow access or change it later, the system will automatically return the language set on system level.

**Comment by xhruso00** [comment]
@bguidolim Please read my post again. I did the reverse engineering where I mentioned private frameworks. Found that the result of the call is WRONG as it returns postal address. It has nothing to do with private frameworks neither permissions checks.
