### ISSUE TITLE
Privacy manifest

### ISSUE THREAD

**Issue by yunsanch** [marmelroy/PhoneNumberKit#758]
would you be adding a privacy manifest, as required by apple? by when would this be done?

**Comment by unnamedd** [comment]
Mate, the project is open source. Every single contributor made the work voluntarily, and this is greatly appreciated. If there is something you are missing, don’t just be a consumer; contribute to it instead of requesting a timeline for implementation. No one is being paid to write code for you, so please be kind and give your contribution.

**Comment by bguidolim** [comment]
In addition to what @unnamedd said, it always worth to check what the open source library you use is doing before adding to your project, then you would be able to see that the privacy manifest was already integrated with #746 and #748
